"""Generate the frozen 20-mutant set for run 3 from subject3/duration.py.

Each mutant is one behaviour change, applied as an anchored text substitution.
EVERY anchor is asserted to occur EXACTLY ONCE before it is replaced: Python's
str.replace() silently no-ops on a mismatch, which in this corpus has twice
produced an edit that appeared applied and was not. A silent no-op here would
emit a mutant identical to the reference -- unkillable, and invisible.

The set is graded on purpose. Some mutants die to any honest suite; some need a
case a careless suite skips. Run `python3 make_mutants3.py --check` to confirm
the committed files still match what this script produces.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REF = os.path.join(HERE, "subject3", "duration.py")
OUT = os.path.join(HERE, "mutants3")

MUTANTS = [
    ("m01", "parse: total bound off by one, so 360000 seconds is accepted",
     "    if total >= _MAX:", "    if total > _MAX:"),
    ("m02", "parse: the leading-zero rule is dropped, so '01s' is accepted",
     '        if len(digits) > 1 and digits[0] == "0":\n            raise ValueError("not a duration string")\n',
     ""),
    ("m03", "parse: unit order and uniqueness unenforced, so '1s 1h' is accepted",
     "        if index < seen:", "        if index < 0:"),
    ("m04", "parse: the sub-60 rule is off by one, so '1h 60m' is accepted",
     "and value >= 60:", "and value > 60:"),
    ("m05", "parse: the sub-60 rule hits the first component too, rejecting '90m'",
     "        if position > 0 and index > 0 and value >= 60:",
     "        if index > 0 and value >= 60:"),
    ("m06", "parse: splits on any whitespace run, so '1h  30m' is accepted",
     '    parts = text.split(" ")', "    parts = text.split()"),
    ("m07", "format: zero becomes the empty string",
     '    if not out:\n        return "0s"\n', ""),
    ("m08", "format: zero becomes '0h'",
     '        return "0s"', '        return "0h"'),
    ("m09", "format: zero components are emitted, so 3600 is '1h 0m 0s'",
     "        if value:\n            out.append", "        if True:\n            out.append"),
    ("m10", "format: upper bound off by one, so 360000 is formatted",
     "    if seconds < 0 or seconds >= _MAX:", "    if seconds < 0 or seconds > _MAX:"),
    ("m11", "format: negative seconds are no longer rejected",
     "    if seconds < 0 or seconds >= _MAX:", "    if seconds >= _MAX:"),
    ("m12", "format: the type check is dropped, so a float reaches the arithmetic",
     "    if isinstance(seconds, bool) or not isinstance(seconds, int):\n        raise TypeError(\"not an integer\")\n",
     ""),
    ("m13", "the hour is 360 seconds, not 3600",
     '_UNITS = (("h", 3600), ("m", 60), ("s", 1))', '_UNITS = (("h", 360), ("m", 60), ("s", 1))'),
    ("m14", "parse: unit letters are case-folded, so '1H' is accepted",
     "        unit, digits = part[-1:], part[:-1]",
     "        unit, digits = part[-1:].lower(), part[:-1]"),
    ("m15", "parse: a non-str raises AttributeError instead of ValueError",
     '    if not isinstance(text, str):\n        raise ValueError("not a duration string")\n', ""),
    ("m16", "format: units are consumed smallest-first",
     "    for unit, size in _UNITS:", "    for unit, size in reversed(_UNITS):"),
    ("m17", "parse: non-ascii decimal digits are accepted",
     "        if not digits.isascii() or not digits.isdigit():",
     "        if not digits.isdigit():"),
    ("m18", "format: a bool is treated as an int, so True formats as '1s'",
     "    if isinstance(seconds, bool) or not isinstance(seconds, int):",
     "    if not isinstance(seconds, int):"),
    ("m19", "parse: one leading zero is tolerated, so '01s' passes but '001s' does not",
     "        if len(digits) > 1 and digits[0] == \"0\":",
     "        if len(digits) > 2 and digits[0] == \"0\":"),
    ("m20", "format: component values are zero-padded to two digits",
     "            out.append(str(value) + unit)",
     '            out.append("%02d%s" % (value, unit))'),
]


def build(name, why, anchor, replacement, src):
    n = src.count(anchor)
    if n != 1:
        raise SystemExit(f"*** {name}: anchor occurs {n} times, want exactly 1:\n{anchor!r}")
    out = src.replace(anchor, replacement)
    if out == src:
        raise SystemExit(f"*** {name}: substitution was a no-op")
    header = f'# MUTANT {name}: {why}\n# Generated by make_mutants3.py. Do not edit by hand.\n'
    return header + out


def main():
    src = open(REF).read()
    check = "--check" in sys.argv
    bad = 0
    for name, why, anchor, replacement in MUTANTS:
        text = build(name, why, anchor, replacement, src)
        path = os.path.join(OUT, name + ".py")
        if check:
            have = open(path).read() if os.path.exists(path) else None
            if have != text:
                print(f"*** {name}: committed file differs from the generator")
                bad += 1
        else:
            os.makedirs(OUT, exist_ok=True)
            with open(path, "w") as fh:
                fh.write(text)
    if check:
        print("mutant set matches the generator" if not bad else f"*** {bad} mutant(s) drifted")
        return 1 if bad else 0
    print(f"wrote {len(MUTANTS)} mutants to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
